Leaderboard page ranks books and lists number of members who have rea…
DevBetterCom/DevBetterWeb pull request #148
Opened 2020-11-04 19:03 UTC by ilyanaDev

…d them. It also includes a link to purchase the book.

Fixes #146

2020-11-04 22:12 UTC, ardalis commented on src/DevBetterWeb.Web/Pages/Leaderboard/Index.cshtml
> +                                <a>Member</a>
Why did you wrap this in <a> tags if it isn't a link? If you just needed Razor to understand it's HTML content not C# code, use a <span> or read this thread:
https://stackoverflow.com/questions/27284734/render-a-string-as-html-in-c-sharp-razor (don't use Html.Raw)

2020-11-04 22:12 UTC, ardalis commented on src/DevBetterWeb.Web/Pages/Leaderboard/Index.cshtml.cs
> +        .ThenBy(book => book.Title)
Looks good!

2020-11-04 22:12 UTC, ardalis requested changes
Fix <a> then good to go.

2020-11-05 19:45 UTC, ilyanaDev commented
Fixed

2020-11-05 20:25 UTC, ardalis approved these changes

2020-11-05 20:25 UTC, merged