Signups report
DevBetterCom/DevBetterWeb pull request #274
Opened 2021-04-29 19:16 UTC by ilyanaDev

fixes #179

2021-04-29 20:45 UTC, ardalis requested changes
Overall looks good. I assume I probably need to take your other data schema change PR before this one. One minor rename change.

2021-04-29 20:45 UTC, ardalis commented on src/DevBetterWeb.Core/Entities/BillingActivity.cs
> +  public class BillingActivity : BaseEntity, IAggregateRoot
I wonder if BillingActivity makes sense as an aggregate root, or if it should simply be a collection on Member, which is already an Aggregate Root. But, I think we probably aren't using aggregates effectively yet in this solution so I'll probably let this go for this PR.

2021-04-29 20:45 UTC, ardalis commented on src/DevBetterWeb.Core/Interfaces/ICSVService.cs
> +    byte[] GetCSVByteArrayFromList(List<BillingActivity> billingActivities);
Renam CSV to Csv throughout.
`ICSVService` => `ICsvService`
etc.

2021-04-29 20:47 UTC, ardalis reviewed
Don't forget CSVService =-> CsvService

2021-04-29 20:51 UTC, ardalis approved these changes

2021-05-06 16:24 UTC, ilyanaDev commented
@ardalis  can this be merged?

2021-05-06 16:56 UTC, merged

2021-05-06 16:56 UTC, ardalis commented
Hopefully this doesn't break anything...